# Generated by Django 5.1 on 2024-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('account_id', models.CharField(max_length=36)),
                ('invoice_month', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('usage_date', models.DateField()),
                ('usage_amount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('cost_discount', models.FloatField(default=0)),
                ('credit_discount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'tb_billing',
            },
        ),
        migrations.CreateModel(
            name='ChargeCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=36)),
                ('charge_code', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tb_charge_code',
            },
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'tb_currency',
            },
        ),
    ]
